# Generated by Django 6.0.5 on 2026-05-31 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_playlist_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('channel_title', models.CharField(max_length=500)),
                ('thumbnail_url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('video_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('oauth', 'OAuth'), ('url', 'URL')], max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'youtube_playlist_id')},
            },
        ),
        migrations.CreateModel(
            name='YouTubeOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.BinaryField()),
                ('refresh_token', models.BinaryField(blank=True, null=True)),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('channel_title', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=50)),
                ('thumbnail_url', models.URLField(max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.BigIntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.playlist')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('playlist', 'youtube_video_id')},
            },
        ),
    ]
