# Generated by Django 6.0.5 on 2026-06-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    "ALTER TABLE api_playlist RENAME COLUMN source_type TO source;"
                ),
            ],
            reverse_sql=[
                (
                    "ALTER TABLE api_playlist RENAME COLUMN source TO source_type;"
                ),
            ],
            state_operations=[
                # No state change needed — the model already defines "source"
            ],
        ),
    ]
