# Generated by Django 6.0.5 on 2026-06-04 01:48

from django.db import migrations


def _columns(schema_editor, table_name):
    return {
        column.name
        for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(),
            table_name,
        )
    }


def rename_source_type_to_source(apps, schema_editor):
    columns = _columns(schema_editor, "api_playlist")
    if "source_type" in columns and "source" not in columns:
        schema_editor.execute(
            "ALTER TABLE api_playlist RENAME COLUMN source_type TO source;"
        )


def rename_source_to_source_type(apps, schema_editor):
    columns = _columns(schema_editor, "api_playlist")
    if "source" in columns and "source_type" not in columns:
        schema_editor.execute(
            "ALTER TABLE api_playlist RENAME COLUMN source TO source_type;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            rename_source_type_to_source,
            rename_source_to_source_type,
        ),
    ]
