# Generated by Django 6.0.5 on 2026-06-04 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_source_type_to_source'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE api_playlist DROP COLUMN is_deleted;",
                "ALTER TABLE api_playlist DROP COLUMN is_hidden;",
                "ALTER TABLE api_playlist DROP COLUMN is_unlinked;",
            ],
            reverse_sql=[
                "ALTER TABLE api_playlist ADD COLUMN is_deleted bool NOT NULL DEFAULT 0;",
                "ALTER TABLE api_playlist ADD COLUMN is_hidden bool NOT NULL DEFAULT 0;",
                "ALTER TABLE api_playlist ADD COLUMN is_unlinked bool NOT NULL DEFAULT 0;",
            ],
        ),
    ]
