# Generated by Django 6.0.5 on 2026-05-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_playlist_flags_and_videonote'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
