# Generated by Django 6.0.5 on 2026-06-04 01:52

from django.db import migrations


def _columns(schema_editor, table_name):
    return {
        column.name
        for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(),
            table_name,
        )
    }


def drop_stale_playlist_columns(apps, schema_editor):
    columns = _columns(schema_editor, "api_playlist")
    for column_name in ["is_deleted", "is_hidden", "is_unlinked"]:
        if column_name in columns:
            schema_editor.execute(f"ALTER TABLE api_playlist DROP COLUMN {column_name};")


def restore_stale_playlist_columns(apps, schema_editor):
    columns = _columns(schema_editor, "api_playlist")
    for column_name in ["is_deleted", "is_hidden", "is_unlinked"]:
        if column_name not in columns:
            schema_editor.execute(
                f"ALTER TABLE api_playlist ADD COLUMN {column_name} bool NOT NULL DEFAULT 0;"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_source_type_to_source'),
    ]

    operations = [
        migrations.RunPython(
            drop_stale_playlist_columns,
            restore_stale_playlist_columns,
        ),
    ]
