# Generated by Django 6.0.5 on 2026-06-04 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_drop_stale_columns'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE api_video ADD COLUMN updated_at datetime NULL;",
                "ALTER TABLE api_video DROP COLUMN is_deleted;",
                "ALTER TABLE api_video DROP COLUMN is_removed;",
            ],
            reverse_sql=[
                "ALTER TABLE api_video ADD COLUMN is_deleted bool NOT NULL DEFAULT 0;",
                "ALTER TABLE api_video ADD COLUMN is_removed bool NOT NULL DEFAULT 0;",
            ],
        ),
    ]
